version: '3.9'
services:
  app:
    image: yiisoftware/yii2-php:8.1-apache
    networks:
      - regular-library-net
      - library-net
    environment:
      APP_ENV: dev
      COMPOSER_ALLOW_SUPERUSER: 1
      FRONTEND_URL: 'http://localhost:8030'
      GH_REPO_URL: 'https://github.com/terratensor/regular-library'
      POSTGRES_HOST: postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
      POSTGRES_DB: common-library
      PAGE_SIZE: 50
      URL_SHORTENER_HOST: url-shortener:8000
      URL_SHORTENER_URL: http://localhost
      COOKIE_DOMAIN: localhost
      COOKIE_VALIDATION_KEY_FILE: /run/secrets/app_cookie_validation_key
      MANTICORE_DB_NAME_COMMON: library
      MANTICORE_MAX_MATCHES: 1000
      SHORT_LINK_ENABLE: 0
      CLEAN_DESIGN: 1
    secrets:
      - app_db_password
      - app_cookie_validation_key
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./app:/app:delegated
    ports:
      - '8030:80'

  postgres:
    container_name: regular-library-postgres
    image: postgres:15.1-alpine
    ports:
      - "54322:5432"
    environment:
      APP_ENV: dev
      POSTGRES_HOST: postgres
      POSTGRES_USER: app
      POSTGRES_DB: common-library
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
    secrets:
      - app_db_password
    networks:
      - regular-library-net
    volumes:
      - postgres:/var/lib/postgresql/data

secrets:
  app_db_password:
    file: ./docker/development/secrets/app_db_password
  app_cookie_validation_key:
    file: ./docker/development/secrets/app_cookie_validation_key

volumes:
  postgres:

networks:
  regular-library-net:
    name: regular-library-net
  library-net:
    name: library-net
