services:
  app:
    image: yiisoftware/yii2-php:8.3-apache
    networks:
      - library-net
    environment:
      APP_ENV: dev 
      COMPOSER_ALLOW_SUPERUSER: 1
      FRONTEND_URL: 'http://localhost:8030'
      GH_REPO_URL: 'https://github.com/terratensor/regular-library'
      PAGE_SIZE: 50
      COOKIE_DOMAIN: localhost
      COOKIE_VALIDATION_KEY_FILE: /run/secrets/app_cookie_validation_key
      MANTICORE_DB_NAME_COMMON: library
      MANTICORE_MAX_MATCHES: 1000
      CLEAN_DESIGN: 1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./app:/app:delegated
      - ./app/data:/app/data
    ports:
      - '8030:80'

  # manticore:
  #   container_name: regular-library-manticore
  #   image: manticoresearch/manticore
  #   environment:
  #     - EXTRA=1
  #   ports:
  #     - "127.0.0.1:9316:9306"
  #     - "127.0.0.1:9318:9308"
  #     - "127.0.0.1:9322:9312"

  #   cap_add:
  #     - IPC_LOCK
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 65535
  #       hard: 65535
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   networks:
  #      - library-net
  #   volumes:
  #     - manticore:/var/lib/manticore
  #     - manticore:/var/log/manticore

networks:
  library-net:
    name: library-net
