version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    environment:
      APP_ENV: dev
      FRONTEND_URL: 'http://localhost:8000'
      GH_REPO_URL: 'https://github.com/terratensor/kob-library-app'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
